export const DATA = [
   {
      "id": 1,
      "date": "09-1-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 2,
      "date": "09-02-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 3,
      "date": "09-03-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 4,
      "date": "09-04-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 5,
      "date": "09-05-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 6,
      "date": "09-06-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 7,
      "date": "09-07-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 8,
      "date": "09-08-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 9,
      "date": "09-09-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 10,
      "date": "09-10-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 11,
      "date": "09-11-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 12,
      "date": "09-12-2022",
      "type": "cash",
      "category": 'LPG',
      "amount": 1000,
      "note": "Pillow with covers.",
   },
   {
      "id": 13,
      "date": "09-12-2022",
      "type": "cash",
      "category": 'Bike',
      "amount": 50000,
      "note": "Downpayment for bike",
   },
]